name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Prepare minimal training data
        run: |
          mkdir -p train
          echo "hello world" > train/train.txt

      - name: Install dependencies
        run: |
          # Install from repo requirements if present (non-failing)
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          # Core deps for tests and tiny transformer
          pip install pytest
          pip install "jax[cpu]" jaxlib
          pip install flax optax

      - name: Run tests
        run: |
          pytest -q
